---
title: java异常处理
date: 2023-05-10
tags: 
  - Java
categories: 
  - 后端开发
  - Java开发
  - JavaSE
---



在java中，导致程序不能正确运行的，有异常和错误。

## 异常和错误

首先区分一下异常和错误

### 错误

**Error（错误）:程序无法处理，通常指程序中出现的严重问题。**

- 例如java.lang.VirtualMachineError（Java虚拟机运行错误）：当 Java虚拟机崩溃或用尽了它继续操作所需的资源时，抛出该错误
- 例如java.lang.StackOverflowError（栈溢出错误）：当应用程序递归太深而发生堆栈溢出时，抛出该错误。
- 例如java.lang.OutOfMemoryError（内存溢出）：内存溢出或没有可用的内存提供给垃圾回收器时，产生这个错误。

Error（错误）是不可查的，而且也常常在应用程序的控制和处理能力之外，因此当Error（错误）出现时，程序会立即奔溃，Java虚拟机立即停止运行。

注意错误是不能被程序处理的。

### **异常**

是指程序本身可以处理的异常（可以向上抛出或者捕获处理）。

Java处理异常的默认方式是`中断处理`。

比如说，代码少了一个分号，那么运行出来结果是提示是错误 java.lang.Error；如果用System.out.println(11/0)，那么你是因为你用0做了除数，会抛出 java.lang.ArithmeticException 的异常。

既然错误的原因有很多，描述错误的类也有很多，那么这种情况就产生了一个大的家族/体系，**这里面全都是异常错误类，我们叫做异常体系**。
对于异常体系而言，大家都是错误，只不过所产生的原因不太一样，不断的进行向上抽取共性，**最终抽出Throwable这个接口（可以被抛出的），但凡是异常对象，无论原因，都可以被抛出。**

![image-20230510215603510](https://typora-1309665611.cos.ap-nanjing.myqcloud.com/typora/image-20230510215603510.png)    Throwable类是 Java 语言中所有错误或异常的超类，只有当对象是此类（或其子类之一)的实例时，才能通过 Java 虚拟机或者 Java throw 语句抛出。
异常是对象，而对象都采用类来定义。异常的根类是 java.lang.Throwable。

>**Java用关键字extends表示继承**。在Java中，所有的继承都是公有继承，而没有C++中的私有继承和保护继承。
>
>已存在的类称为超类或者父类或者基类(**super   class**)，新类称为子类（subclass)。超类和子类是 Java 程序员最常用的两个术语。在设计类的时候，应该将通用的方法放在超类中， 而将具有特殊用途的方法放在子类中
>
>私有继承和公有继承是C++的概念，其主要区别在于子类对基类（java超类）的访问权限，比如共有继承的子类不能访问父类的私有属性与方法。

如上所示，异常分为运行异常和编译异常

- **运行异常：**顾名思义，是程序运行时才会出现的异常。运行异常是java.lang.RuntimeException类及其子类的统称。如NullPointerException（空指针异常）、IndexOutOfBoundsException（数组下标越界异常）等。运行异常一般是由程序逻辑错误导致的，可以通过捕获处理或向上抛出。运行异常的特点是Java编译器不会检查它，也就是说，当程序中可能出现运行异常，也会被编译通过。
- **编译异常：**顾名思义，是程序编译时就会出现的异常。编译异常是java.lang.RuntimeException以外的异常。编译异常必须进行处理，如果不处理，程序就不能编译通过

#### 异常处理

##### **try…catch…finally** : 捕获异常并处理

使用格式：

~~~java
try{
     编写可能会出现异常的代码
}catch(异常类型  e){
     处理异常的代码
     //记录日志/打印异常信息/继续抛出异常
}
~~~

- **面试题**： 如果try{} 里有一个 return 语句，那么finalfly{} 里的代码会不会被执行，什么时候被执行，在 return 前还是后?
- 会执行，在return前执行。当程序检测到try{}中的return语句时，它会在return语句执行前，检查是否finalfly{}语句，如果有，就执行finalfly{}语句，如果没有，直接返回。如果finalfly{}里也有return 语句，那么try{}中的return语句将失效。

##### **throws**：声明异常

声明异常：声明一个异常，并告知调用者。关键字throws运用于方法声明上，表示当前方法不处理异常，而是提醒该方法的调用者来处理异常(捕获处理或者继续抛出)。

如果方法内部throw一个编译异常，而没有捕获处理，那么必须在方法体上通过throws进行声明，让调用者处理。

>**`因为运行异常有jvm处理，编译异常jvm是不管的，必须自定义处理逻辑（捕获处理或者上抛）。`**

~~~java
import java.io.FileNotFoundException;

public class Demo01 {
    public static void main(String[] args) throws FileNotFoundException {
      eat("bird.avi");
    }
    /**
     * 学习知识，充实自己
     */
    public static void eat(String path) throws FileNotFoundException {
        if (!path.equals("apple")) {
            throw new FileNotFoundException("FileNotFoundException");
        }
        /**
        *可以接着写if，进行多个异常处理逻辑
        */
        
    }
}
~~~



参考

>https://blog.csdn.net/single_0910/article/details/114258581
>
>https://blog.csdn.net/m0_46316970/article/details/119898445