---
title: mysql遇到的一些问题
date: 2023-06-16
tags: 
  - null
categories: 
  - 大数据
  - MySQL
---

## 1连接超时，无效连接？

message

~~~shell
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 310,633,588 milliseconds ago. The last packet sent successfully to the server was 310,633,589 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
~~~

使用的durid，配置文件如下

~~~yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.245.142.253:3306/test?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 数据源专有配置
    # 不是druid-spring-boot-starter依赖，SpringBoot默认是不注入druid数据源专有属性值的，需要自己绑定
    initial-size: 2
    #最小连接池数量
    min-idle: 8
    #最大连接池数量 maxIdle已经不再使用
    max-active: 20
    #获取连接时最大等待时间，单位毫秒
    max-wait: 60000

    validation-query: SELECT 1
    # 检测连接是否有效的超时时间，单位秒
    validation-query-timeout: 5
    # 是否自动回收超时连接
    remove-abandoned: true
    # 超时时间，单位秒
    remove-abandoned-timeout: 180
    # 是否自动重新连接
    connection-properties: autoReconnect=true

~~~

配置类：

~~~java
package com.inet.config;

import com.alibaba.druid.pool.DruidDataSource;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import javax.sql.DataSource;

/**
 * @Description: Durid的配置文件，必须手动设置配置类，yaml的durid数据库连接池的配置才生效
 */
@Configuration
public class DuridConfig {

    @Bean
    @ConfigurationProperties(prefix = "spring.datasource")
    @ConditionalOnProperty(name = "spring.datasource.type", havingValue = "com.alibaba.druid.pool.DruidDataSource")
    public DataSource durid(){
        return new DruidDataSource();
    }
}

~~~

这个错误是由于与MySQL服务器之间的连接超时引起的。根据错误消息，服务器配置的'wait_timeout'值设置得比较小，导致在最后一次成功接收和发送数据包之后超过了该超时时间。

网上找了半天，一点用没有，因此还是开始自己乱搞

首先进入mysql,` show full processlist;`,发现这里有两个连接time是0，却是sleep，再想起前几天我用到过着这个连接，因此猜想，正是这两个连接过期了，而我还去重连，导致一直抛出错误

![image-20230616100934253](https://typora-1309665611.cos.ap-nanjing.myqcloud.com/typora/image-20230616100934253.png)

在这行代码中，需要把数据插入sbom_store的数据库中，因此就是在这里发生了连接已经超时的错误。

![image-20230616101128687](https://typora-1309665611.cos.ap-nanjing.myqcloud.com/typora/image-20230616101128687.png)

尝试删了mysql数据库连接，但发现其实是新建了连接的，但是为什么还是报出这个错误？

![image-20230616102202818](https://typora-1309665611.cos.ap-nanjing.myqcloud.com/typora/image-20230616102202818.png)

此时我才明白，我配置的连接是sbom的，里面存的是我要认证的用户，**而我在hugegraph配置文件里设置的sbom_store来当存储数据库，所以我改配置文件根本不会影响到他！**

最后想来可能是hugegraph自己用mysql做后端存储时也需要配置相关的连接信息，但并没有说怎么配置，所以最后改回用rockdb来当hugegraph的后端了。